## @file
#  dsc include file for Configuration Manager
#
#  Copyright (c) 2017 - 2020, Arm Limited. All rights reserved.<BR>
#  Copyright (C) 2023, Phytium Technology Co., Ltd. All rights reserved.<BR>
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]

[BuildOptions]

[LibraryClasses.common]

[Components.common]
  # Configuration Manager
  Silicon/Phytium/PhytiumCommonPkg/ConfigurationManager/ConfigurationManagerDxe/ConfigurationManagerDxe.inf
